# Generated by Django 4.0 on 2022-10-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='url')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='Город проживания')),
                ('school', models.CharField(blank=True, max_length=200, verbose_name='Школа')),
                ('grade', models.IntegerField(blank=True, verbose_name='Класс')),
                ('tests', models.ManyToManyField(blank=True, to='app_test.Test', verbose_name='Тесты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Профиль ользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
