# Generated by Django 4.0 on 2022-10-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликованно')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Отредактированно')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=20, verbose_name='Имя автора')),
                ('description', models.TextField(default='', verbose_name='Комментарий')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.new', verbose_name='Новость')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
