# Generated by Django 4.0 on 2022-10-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='user_name',
            field=models.CharField(blank=True, default='Аноним', max_length=20, verbose_name='Имя автора'),
        ),
    ]
